// generated by 'vyn gen' — do not edit by hand.
import "./features/notes/notes.actions.ts";
import "./features/agent/agent.actions.ts";
import "./features/agent/deep-research.actions.ts";
import "./features/inbox/inbox.actions.ts";

export const routes = [
	{ pattern: "/", file: "/routes/index.html" },
	{ pattern: "/research/:runId", file: "/routes/research.html" },
] as const;
