// generated by 'vyn gen' — do not edit.
// Registers every *.component.ts under public/. Tag = basename.
// Folders are purely organizational.

import { defineComponent } from "@vynjs/client";

import __cmp_0 from "./public/components/theme-toggle.component.ts";
defineComponent("theme-toggle", __cmp_0);
import __cmp_1 from "./public/components/todo-row.component.ts";
defineComponent("todo-row", __cmp_1);
