// generated by 'vyn gen' — do not edit.
// Imports every *.actions.ts, then calls rebindActions so each
// export's registry name becomes `${folder}.${exportName}`. Apps
// don't need to write `name: "todos.add"` on every action.

import { rebindActions } from "@vynjs/core";

import * as $todos_0 from "./features/todos/todos.actions.ts";

// Re-key registered actions so they answer at canonical names.
rebindActions("todos", $todos_0);

import type { RouteMount } from "@vynjs/client";

// File-based routes. Each *.html in public/routes/ is a view;
// a sibling *.ts (same basename) is an optional controller —
// its default export receives the mounted DOM and params and
// may return a cleanup function.
const __view_0 =
	'<section class="card">\n\t<header class="card-head">\n\t\t<h2>Live todos</h2>\n\t\t<p class="hint">Edit <code>features/todos/todos.actions.ts</code> and save.\n\t\t\tUpdates stream to every connected client over a WebSocket.</p>\n\t</header>\n\n\t<form id="new-form" autocomplete="off">\n\t\t<input id="new-title" type="text" placeholder="Add a todo…" autofocus>\n\t\t<button>Add</button>\n\t</form>\n\n\t<ul id="todos" aria-live="polite"></ul>\n\n\t<footer class="card-foot">\n\t\t<span id="count"></span>\n\t\t<a href="/">← Home</a>\n\t</footer>\n</section>\n';
const __view_1 =
	'<section class="hero">\n\t<div class="logo" aria-hidden="true">\n\t\t<svg viewBox="0 0 64 64" width="72" height="72">\n\t\t\t<defs>\n\t\t\t\t<linearGradient id="g" x1="0" y1="0" x2="1" y2="1">\n\t\t\t\t\t<stop offset="0%"  stop-color="#6366f1"/>\n\t\t\t\t\t<stop offset="100%" stop-color="#4f46e5"/>\n\t\t\t\t</linearGradient>\n\t\t\t</defs>\n\t\t\t<rect x="4" y="4" width="56" height="56" rx="14" fill="url(#g)"/>\n\t\t\t<path d="M18 26 L29 42 L46 18" stroke="white" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" fill="none"/>\n\t\t</svg>\n\t</div>\n\t<h1>vyn</h1>\n\t<p class="tagline">A small full-stack TypeScript framework for Deno.<br>\n\t\tFive primitives. Realtime over WebSocket. Zero ceremony.</p>\n\n\t<div class="pills">\n\t\t<span class="pill"><svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><path d="M5 13l4 4L19 7" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg> Deno-native</span>\n\t\t<span class="pill"><svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><path d="M13 2L4 14h6l-1 8 9-12h-6z" fill="currentColor"/></svg> WebSocket realtime</span>\n\t\t<span class="pill"><svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M8 12l3 3 5-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg> Schemas everywhere</span>\n\t</div>\n\n\t<div class="ctas">\n\t\t<a class="btn btn-primary" href="/todos">See it live →</a>\n\t\t<a class="btn"             href="https://rognes.guru/vyn" target="_blank" rel="noopener">Docs ↗</a>\n\t</div>\n\n\t<pre class="quickstart"><code>$ deno create jsr:@vynjs/create -- my-app</code></pre>\n</section>\n';

export const routes = [
	{
		path: "/todos",
		view: __view_0,
		mount: ((el, params) => import("./public/routes/todos.ts").then((m) => (m.default as RouteMount)(el, params))) as RouteMount,
	},
	{ path: "/", view: __view_1 },
] as const;

export type AppRouter = {
	"todos": typeof $todos_0;
};
