// generated by 'vyn gen' — do not edit by hand.
import "./features/todos/todos.actions.ts";

export const routes = [
	{ pattern: "/", file: "/routes/index.html" },
] as const;

import type * as todos from "./features/todos/todos.actions.ts";
export type AppRouter = { todos: typeof todos };
