#!/usr/bin/env -S deno run -A --unstable-node-globals --unstable-bare-node-builtins
// vyn CLI — Deno-only. Subcommands: init, dev, build, check, gen, mcp, worker.

import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { encodeHex } from "jsr:@std/encoding@^1/hex";
import { TEMPLATES } from "./templates.gen.ts";

const cwd = Deno.cwd();
const argv = Deno.args.slice();
const cmd = argv[0];

async function main() {
	switch (cmd) {
		case "init":
			return init();
		case "dev":
			return dev();
		case "build":
			return build();
		case "check":
			return check();
		case "gen":
			return gen();
		case "mcp":
			return mcp();
		case "worker":
			return worker();
		default:
			help();
			Deno.exit(cmd ? 1 : 0);
	}
}

function help() {
	console.log(`vyn — small full-stack framework

Usage:
  vyn init                  scaffold a hello-world app in the current dir
  vyn dev                   run the dev server (watch + reload)
  vyn build                 build the production bundle
  vyn check                 type-check the project ('deno check')
  vyn gen                   regenerate _vyn.gen.ts (action barrel + routes)
  vyn mcp --stdio           expose the app's MCP server on stdio
  vyn worker                run the job worker (no HTTP server)
`);
}

// ─── init ────────────────────────────────────────────────────────────

async function init() {
	// Optional second arg = target directory. `vyn init my-app` scaffolds
	// into ./my-app/ (created if missing); `vyn init` scaffolds into the
	// current directory.
	const targetArg = argv[1];
	let targetDir = cwd;
	if (targetArg) {
		targetDir = join(cwd, targetArg);
		if (existsSync(targetDir)) {
			console.error(`error: ${targetArg} already exists`);
			Deno.exit(1);
		}
		await mkdir(targetDir, { recursive: true });
	}
	const name = basename(targetDir);
	const VYN = "jsr:@vynjs/cli@^0.2";
	const files: Array<[string, string]> = [
		[
			"deno.json",
			JSON.stringify(
				{
					tasks: {
						dev: `deno run -A --unstable-node-globals --unstable-bare-node-builtins ${VYN} dev`,
						start: `deno run -A --unstable-node-globals --unstable-bare-node-builtins server.ts`,
						gen: `deno run -A ${VYN} gen`,
						build: `deno run -A ${VYN} build`,
						check: `deno check server.ts`,
						mcp: `deno run -A ${VYN} mcp --stdio`,
					},
					imports: {
						"@vynjs/core": "jsr:@vynjs/core@^0.2",
						"@vynjs/server": "jsr:@vynjs/server@^0.2",
						"@vynjs/client": "jsr:@vynjs/client@^0.2",
						"@vynjs/ui": "jsr:@vynjs/ui@^0.2",
					},
					nodeModulesDir: "auto",
					compilerOptions: {
						lib: ["deno.window", "dom", "dom.iterable", "esnext"],
						strict: true,
					},
					unstable: ["node-globals", "bare-node-builtins"],
				},
				null,
				2,
			) + "\n",
		],
		[".gitignore", `node_modules\n.env\n.env.*\n!.env.example\n*.db\ndist\n`],
		[
			"README.md",
			`# ${name}\n\nA Vyn app.\n\n\`\`\`sh\ndeno task dev\n\`\`\`\n`,
		],
	];
	// Template files (server.ts, public/, features/, components — everything
	// non-config) are baked into templates.gen.ts from packages/cli/template/.
	// Update the template, run `deno task build:templates`, ship.
	for (const [rel, content] of Object.entries(TEMPLATES)) {
		files.push([rel, content.replaceAll("__VYN_APP_NAME__", name)]);
	}
	// Empty stubs so server.ts + main.ts parse before the first
	// `vyn gen`. `deno task dev` runs gen on every start and overwrites.
	files.push(
		[
			"_vyn.gen.ts",
			`// generated by 'vyn gen' — do not edit.\nexport const routes = [] as const;\nexport type AppRouter = unknown;\n`,
		],
		["_vyn.client.gen.ts", `// generated by 'vyn gen' — do not edit.\n`],
	);

	for (const [path, content] of files) {
		const full = join(targetDir, path);
		if (existsSync(full)) {
			console.log(`skip ${path} (exists)`);
			continue;
		}
		await mkdir(dirname(full), { recursive: true });
		await writeFile(full, content);
		console.log(`create ${path}`);
	}

	// Resolve and pin every jsr:@vynjs/* version into deno.lock so the
	// scaffolded app uses today's published versions on first `deno task
	// dev` instead of whatever stale 0.2.x happens to be in the global
	// cache. Using `--reload=jsr:@vynjs` forces a meta refresh so we pick
	// the actual latest published, not a stale-cached older minor.
	console.log(
		"\nResolving @vynjs/* versions (deno install --reload=jsr:@vynjs)…",
	);
	const install = await new Deno.Command("deno", {
		args: ["install", "--reload=jsr:@vynjs"],
		cwd: targetDir,
		stdout: "inherit",
		stderr: "inherit",
	}).output();
	if (install.code !== 0) {
		console.warn(
			"\n[vyn] deno install failed. Run it manually before `deno task dev`.",
		);
	}

	if (targetArg) {
		console.log(`\nDone. Next:\n  cd ${targetArg}\n  deno task dev`);
	} else {
		console.log("\nDone. Next: deno task dev");
	}
}

// ─── dev ─────────────────────────────────────────────────────────────

async function dev() {
	await gen();
	const port = Deno.env.get("PORT") ?? "8000";

	// Watch features/ + public/routes/ for new files; re-run gen.
	const watchTargets = [join(cwd, "features"), join(cwd, "public", "routes")]
		.filter((p) => existsSync(p));
	void watchAndGen(watchTargets);

	const proc = new Deno.Command("deno", {
		args: [
			"run",
			"-A",
			"--watch",
			"--unstable-node-globals",
			"--unstable-bare-node-builtins",
			"server.ts",
		],
		stdout: "inherit",
		stderr: "inherit",
		stdin: "inherit",
		env: {
			...Object.fromEntries(Object.entries(Deno.env.toObject())),
			PORT: port,
			NODE_ENV: "development",
		},
	}).spawn();
	const { code } = await proc.status;
	Deno.exit(code);
}

async function watchAndGen(targets: string[]) {
	if (targets.length === 0) return;
	const watcher = Deno.watchFs(targets);
	let pending: ReturnType<typeof setTimeout> | undefined;
	for await (const ev of watcher) {
		const interesting = ev.paths.some((p) => /\.(actions\.ts|html)$/.test(p));
		if (!interesting) continue;
		if (pending !== undefined) clearTimeout(pending);
		pending = setTimeout(() => {
			void gen();
		}, 100);
	}
}

// ─── build / check / mcp / worker ────────────────────────────────────

async function build() {
	await gen();

	const publicDir = join(cwd, "public");
	if (!existsSync(publicDir)) {
		console.log("[vyn] build: no public/ directory — nothing to bundle.");
		return;
	}

	const entries = await walkFiles(publicDir, /\.ts$/, ["dist"]);
	if (entries.length === 0) {
		console.log(
			"[vyn] build: no .ts entries under public/ — nothing to bundle.",
		);
		return;
	}

	const distDir = join(publicDir, "dist");
	await rm(distDir, { recursive: true, force: true });
	await mkdir(distDir, { recursive: true });

	const manifest: Record<string, string> = {};

	for (const entry of entries) {
		const relTs = "/" + relative(publicDir, entry).replace(/\\/g, "/");
		const srcUrl = relTs.replace(/\.ts$/, ".js");

		const cmd = new Deno.Command(Deno.execPath(), {
			args: [
				"bundle",
				"--platform=browser",
				"--minify",
				entry,
			],
			stdout: "piped",
			stderr: "piped",
		});
		const { code, stdout, stderr } = await cmd.output();
		if (code !== 0) {
			console.error(new TextDecoder().decode(stderr));
			throw new Error(`bundle failed for ${entry}`);
		}
		const bytes = stdout;
		const digest = await crypto.subtle.digest("SHA-256", new Uint8Array(bytes));
		const hash = encodeHex(new Uint8Array(digest)).slice(0, 10);
		const distRel = srcUrl.replace(/\.js$/, `.${hash}.js`);
		const outPath = join(distDir, distRel);
		await mkdir(dirname(outPath), { recursive: true });
		await writeFile(outPath, bytes);
		manifest[srcUrl] = "/dist" + distRel;
		console.log(`  ${srcUrl} → ${manifest[srcUrl]} (${bytes.length} bytes)`);
	}

	await writeFile(
		join(distDir, "manifest.json"),
		JSON.stringify(manifest, null, 2) + "\n",
	);
	console.log(
		`\n[vyn] build: ${entries.length} bundles → public/dist/, manifest at public/dist/manifest.json`,
	);
}

async function check() {
	const proc = new Deno.Command("deno", {
		args: ["check", "server.ts"],
		stdout: "inherit",
		stderr: "inherit",
	}).spawn();
	const { code } = await proc.status;
	Deno.exit(code);
}

async function mcp() {
	const stdio = argv.includes("--stdio");
	if (!stdio) {
		console.log("[vyn] usage: vyn mcp --stdio");
		Deno.exit(1);
	}
	// Boot the app's server.ts so actions register, but never bind a port —
	// we run the MCP loop over stdin/stdout instead.
	Deno.env.set("VYN_MCP_STDIO", "1");
	Deno.env.set("PORT", "0");
	await import(`${cwd}/server.ts`);

	const { registry } = await import("@vynjs/core");
	const decoder = new TextDecoder();
	const buf = new Uint8Array(1024 * 64);
	let pending = "";
	while (true) {
		const n = await Deno.stdin.read(buf);
		if (n === null) break;
		pending += decoder.decode(buf.subarray(0, n), { stream: true });
		let nl: number;
		while ((nl = pending.indexOf("\n")) !== -1) {
			const line = pending.slice(0, nl).trim();
			pending = pending.slice(nl + 1);
			if (!line) continue;
			try {
				const req = JSON.parse(line);
				const res = await handleStdioFrame(req, registry);
				await Deno.stdout.write(
					new TextEncoder().encode(JSON.stringify(res) + "\n"),
				);
			} catch (e) {
				await Deno.stdout.write(
					new TextEncoder().encode(
						JSON.stringify({
							jsonrpc: "2.0",
							id: null,
							error: { code: -32603, message: (e as Error).message },
						}) + "\n",
					),
				);
			}
		}
	}
}

async function handleStdioFrame(req: any, registry: any) {
	const id = req?.id;
	if (req?.method === "initialize") {
		return {
			jsonrpc: "2.0",
			id,
			result: {
				protocolVersion: "2024-11-05",
				capabilities: { tools: {} },
				serverInfo: { name: "@vynjs/cli mcp", version: "0.0.0" },
			},
		};
	}
	if (req?.method === "tools/list") {
		const tools = registry.list().filter((a: any) => a.tool && !a.tool.hidden)
			.map((a: any) => ({
				name: a.name,
				description: a.description ?? "",
				inputSchema: a.input?.schema ?? { type: "object" },
				outputSchema: a.output?.schema ?? { type: "null" },
			}));
		return { jsonrpc: "2.0", id, result: { tools } };
	}
	if (req?.method === "tools/call") {
		const name = req.params?.name;
		const args = req.params?.arguments;
		const action = registry.get(name);
		if (!action) {
			return {
				jsonrpc: "2.0",
				id,
				error: { code: -32601, message: `unknown tool: ${name}` },
			};
		}
		const result = await action.run({ input: args, ctx: {} });
		return {
			jsonrpc: "2.0",
			id,
			result: {
				content: [{ type: "text", text: JSON.stringify(result) }],
				structuredContent: result,
			},
		};
	}
	return {
		jsonrpc: "2.0",
		id,
		error: { code: -32601, message: `unknown method: ${req?.method}` },
	};
}

async function worker() {
	console.log("[vyn] worker: booting app and running flush loop");
	Deno.env.set("VYN_WORKER", "1");
	await import(`${cwd}/server.ts`);
	Deno.addSignalListener("SIGTERM", () => {
		console.log("[vyn worker] shutting down");
		Deno.exit(0);
	});
	await new Promise(() => undefined);
}

// ─── gen — scan filesystem, emit _vyn.gen.ts ─────────────────────────

async function loadVynConfig(): Promise<
	{ actionsRoot?: string; routesRoot?: string }
> {
	const path = join(cwd, "vyn.config.ts");
	if (!existsSync(path)) return {};
	try {
		const mod = await import(path);
		return (mod.default ?? {}) as { actionsRoot?: string; routesRoot?: string };
	} catch (e) {
		console.warn(`[vyn] could not load vyn.config.ts: ${(e as Error).message}`);
		return {};
	}
}

async function gen() {
	const config = await loadVynConfig();
	const featuresDir = join(cwd, config.actionsRoot ?? "features");
	const routesDir = join(cwd, config.routesRoot ?? "public/routes");
	const publicDir = join(cwd, "public");
	const actionFiles = existsSync(featuresDir) ? await walkFiles(featuresDir, /\.actions\.ts$/) : [];
	const routeFiles = existsSync(routesDir) ? await walkFiles(routesDir, /\.html$/) : [];
	// Components live anywhere under public/ — folders are organizational.
	// Tag = basename minus `.component.ts`. Must include a hyphen per HTML spec.
	const componentFiles = existsSync(publicDir) ? await walkFiles(publicDir, /\.component\.ts$/, ["dist"]) : [];

	// Namespace per parent folder name: features/<ns>/<file>.actions.ts → "<ns>"
	// If multiple .actions.ts share a folder, their exports merge into one
	// namespace via TypeScript's intersection of namespace-import types.
	const byNs = new Map<string, string[]>(); // ns → relative paths
	for (const f of actionFiles) {
		const rel = "./" + relative(cwd, f).replace(/\\/g, "/");
		const ns = basename(dirname(f));
		const arr = byNs.get(ns) ?? [];
		arr.push(rel);
		byNs.set(ns, arr);
	}

	const lines: string[] = [
		"// generated by 'vyn gen' — do not edit.",
		"// Imports every *.actions.ts, then calls rebindActions so each",
		"// export's registry name becomes `${folder}.${exportName}`. Apps",
		'// don\'t need to write `name: "todos.add"` on every action.',
		"",
		`import { rebindActions } from "@vynjs/core";`,
		"",
	];

	const nsAliases: { ns: string; aliases: string[]; type: string }[] = [];
	let seq = 0;
	for (const [ns, files] of byNs) {
		const aliases: string[] = [];
		for (const rel of files) {
			const alias = `$${ns.replace(/[^a-zA-Z0-9_]/g, "_")}_${seq++}`;
			aliases.push(alias);
			// Value-position namespace import — triggers module evaluation
			// (registers actions) and powers the AppRouter type below.
			lines.push(`import * as ${alias} from "${rel}";`);
		}
		const type = aliases.length === 1 ? `typeof ${aliases[0]}` : `(${aliases.map((a) => `typeof ${a}`).join(" & ")})`;
		nsAliases.push({ ns, aliases, type });
	}

	lines.push("");
	lines.push("// Re-key registered actions so they answer at canonical names.");
	for (const { ns, aliases } of nsAliases) {
		for (const a of aliases) {
			lines.push(`rebindActions(${JSON.stringify(ns)}, ${a});`);
		}
	}

	lines.push("");
	lines.push(`import type { RouteMount } from "@vynjs/client";`);
	lines.push("");
	lines.push("// File-based routes. Each *.html in public/routes/ is a view;");
	lines.push("// a sibling *.ts (same basename) is an optional controller —");
	lines.push("// its default export receives the mounted DOM and params and");
	lines.push("// may return a cleanup function.");

	const routeEntries: Array<
		{ pattern: string; viewVar: string; ctrlImport?: string }
	> = [];
	let routeSeq = 0;
	for (const f of routeFiles) {
		const rel = relative(routesDir, f).replace(/\\/g, "/").replace(
			/\.html$/,
			"",
		);
		// Files starting with "_" are private (404.html, layouts) — view
		// data is still emitted so main.ts can reference them, but they
		// don't get a pattern in the routes table.
		const base = rel.split("/").pop() ?? "";
		if (base.startsWith("_")) continue;

		const pattern = "/" +
			rel.replace(/\[([^\]]+)\]/g, ":$1").replace(/\/?index$/, "");
		const viewVar = `__view_${routeSeq}`;
		const ctrlPath = f.replace(/\.html$/, ".ts");
		const hasCtrl = existsSync(ctrlPath);
		const ctrlImport = hasCtrl ? "./" + relative(cwd, ctrlPath).replace(/\\/g, "/") : undefined;

		const htmlSrc = await readFile(f, "utf-8");
		lines.push(`const ${viewVar} = ${JSON.stringify(htmlSrc)};`);

		routeEntries.push({ pattern: pattern || "/", viewVar, ctrlImport });
		routeSeq++;
	}

	lines.push("");
	lines.push(`export const routes = [`);
	for (const r of routeEntries) {
		// Lazy controller import — keeps _vyn.gen.ts server-safe (the
		// route's TS file can use browser-only APIs because it never
		// loads until the client router calls mount()).
		const mountField = r.ctrlImport
			? `, mount: ((el, params) => import(${
				JSON.stringify(r.ctrlImport)
			}).then((m) => (m.default as RouteMount)(el, params))) as RouteMount`
			: "";
		lines.push(
			`\t{ path: ${JSON.stringify(r.pattern)}, view: ${r.viewVar}${mountField} },`,
		);
	}
	lines.push("] as const;");
	lines.push("");
	lines.push("export type AppRouter = {");
	for (const { ns, type } of nsAliases) {
		lines.push(`\t${JSON.stringify(ns)}: ${type};`);
	}
	lines.push("};");
	lines.push("");

	await writeFile(join(cwd, "_vyn.gen.ts"), lines.join("\n"));

	// _vyn.client.gen.ts — browser-only barrel: every *.component.ts
	// registered under its basename-derived tag. Split from _vyn.gen.ts
	// because component files use document/HTMLElement at module scope
	// and would crash a server-side import.
	const seenTags = new Map<string, string>(); // tag → file (collision check)
	const clientLines: string[] = [
		"// generated by 'vyn gen' — do not edit.",
		"// Registers every *.component.ts under public/. Tag = basename.",
		"// Folders are purely organizational.",
		"",
		`import { defineComponent } from "@vynjs/client";`,
		"",
	];
	let compSeq = 0;
	for (const f of componentFiles) {
		const base = f.split(/[\\/]/).pop()!.replace(/\.component\.ts$/, "");
		if (!base.includes("-")) {
			throw new Error(
				`[vyn] component tag must contain a hyphen — "${base}" at ${f}`,
			);
		}
		const prev = seenTags.get(base);
		if (prev) {
			throw new Error(
				`[vyn] duplicate component tag "${base}":\n  ${prev}\n  ${f}`,
			);
		}
		seenTags.set(base, f);
		const rel = "./" + relative(cwd, f).replace(/\\/g, "/");
		const alias = `__cmp_${compSeq++}`;
		clientLines.push(`import ${alias} from "${rel}";`);
		clientLines.push(`defineComponent(${JSON.stringify(base)}, ${alias});`);
	}
	await writeFile(
		join(cwd, "_vyn.client.gen.ts"),
		clientLines.join("\n") + "\n",
	);

	console.log(
		`[vyn] gen: wrote _vyn.gen.ts (${actionFiles.length} actions, ${routeFiles.length} routes) + _vyn.client.gen.ts (${componentFiles.length} components)`,
	);
}

async function walkFiles(
	dir: string,
	pattern: RegExp,
	skipDirs: string[] = [],
): Promise<string[]> {
	const entries = await readdir(dir);
	const out: string[] = [];
	for (const name of entries) {
		if (skipDirs.includes(name)) continue;
		const full = join(dir, name);
		const s = await stat(full);
		if (s.isDirectory()) out.push(...await walkFiles(full, pattern, skipDirs));
		else if (pattern.test(name)) out.push(full);
	}
	return out;
}

main().catch((e) => {
	console.error("[vyn]", e);
	Deno.exit(1);
});
