#!/usr/bin/env node
// vyn CLI. Subcommands: init, dev, build, check, gen, mcp, worker.

import { spawn } from "node:child_process";
import { mkdir, writeFile, readdir, stat, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, relative, basename, extname } from "node:path";

const cwd = process.cwd();
const argv = process.argv.slice(2);
const cmd = argv[0];

async function main() {
	switch (cmd) {
		case "init":   return init();
		case "dev":    return dev();
		case "build":  return build();
		case "check":  return check();
		case "gen":    return gen();
		case "mcp":    return mcp();
		case "worker": return worker();
		default:
			help();
			process.exit(cmd ? 1 : 0);
	}
}

function help() {
	console.log(`vyn — small full-stack framework

Usage:
  vyn init                  scaffold a hello-world app in the current dir
  vyn dev                   run the dev server (watch + reload)
  vyn build                 build the production bundle
  vyn check                 type-check the project via tsc
  vyn gen                   regenerate _vyn.gen.ts (action barrel + route params)
  vyn mcp --stdio           expose the app's MCP server on stdio
  vyn worker [--c=N]        run the job worker (no HTTP server)
`);
}

// ─── init ────────────────────────────────────────────────────────────

async function init() {
	const files: Array<[string, string]> = [
		["package.json", JSON.stringify({
			name: basename(cwd),
			type: "module",
			scripts: {
				dev:   "vyn dev",
				build: "vyn build",
				check: "vyn check",
				gen:   "vyn gen",
			},
			dependencies: { "@vyn/server": "*", "@vyn/client": "*", "@vyn/core": "*" },
			devDependencies: { "@vyn/cli": "*", typescript: "^5.7.2" },
		}, null, 2)],
		["tsconfig.json", JSON.stringify({
			compilerOptions: {
				target: "ES2022", module: "ES2022", moduleResolution: "Bundler",
				strict: true, esModuleInterop: true, skipLibCheck: true,
				allowImportingTsExtensions: true, noEmit: true,
			},
		}, null, 2)],
		["server.ts", `import { serve } from "@vyn/server";
import "./_vyn.gen.ts";

serve({ port: Number(process.env.PORT ?? 8000) });
`],
		["public/index.html", `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>${basename(cwd)}</title><link rel="stylesheet" href="/style.css"></head>
<body><main>Hello from Vyn.</main><script type="module" src="/main.js"></script></body>
</html>
`],
		["public/main.js", `console.log("hello vyn");`],
		["public/style.css", `body { font-family: system-ui, sans-serif; padding: 2rem; }`],
		["_vyn.gen.ts", `// generated by 'vyn gen' — do not edit.\nexport {};\n`],
	];

	for (const [path, content] of files) {
		const full = join(cwd, path);
		if (existsSync(full)) { console.log(`skip ${path} (exists)`); continue; }
		await mkdir(dirname(full), { recursive: true });
		await writeFile(full, content);
		console.log(`create ${path}`);
	}
	console.log("\nDone. Next: npm install && npm run dev");
}

// ─── dev ─────────────────────────────────────────────────────────────

async function dev() {
	await gen();
	const port = process.env.PORT ?? "8000";
	const proc = spawn("node", ["--experimental-strip-types", "--watch", "server.ts"], {
		stdio: "inherit",
		env:   { ...process.env, PORT: port, NODE_ENV: "development" },
	});
	proc.on("exit", (code) => process.exit(code ?? 0));
}

// ─── build / check / mcp / worker ────────────────────────────────────

async function build() {
	await gen();
	console.log("[vyn] build: nothing to compile (Node strip-types runs sources directly).");
}

async function check() {
	const proc = spawn("npx", ["-y", "tsc", "--noEmit"], { stdio: "inherit" });
	proc.on("exit", (code) => process.exit(code ?? 0));
}

async function mcp() {
	const stdio = argv.includes("--stdio");
	if (!stdio) {
		console.log("[vyn] usage: vyn mcp --stdio");
		process.exit(1);
	}
	// Boot the app's server.ts so actions register, but never bind a port —
	// we run the MCP loop over stdin/stdout instead.
	process.env.VYN_MCP_STDIO = "1";
	process.env.PORT          = "0";
	const serverModule = await import(`${cwd}/server.ts`);
	void serverModule;

	const { registry } = await import("@vyn/core");
	const readline = await import("node:readline");
	const rl = readline.createInterface({ input: process.stdin });
	for await (const line of rl) {
		try {
			const req = JSON.parse(line);
			const res = await handleStdioFrame(req, registry);
			process.stdout.write(JSON.stringify(res) + "\n");
		} catch (e) {
			process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32603, message: (e as Error).message } }) + "\n");
		}
	}
}

async function handleStdioFrame(req: any, registry: any) {
	const id = req?.id;
	if (req?.method === "initialize") {
		return { jsonrpc: "2.0", id, result: { protocolVersion: "2024-11-05", capabilities: { tools: {} }, serverInfo: { name: "@vyn/cli mcp", version: "0.0.0" } } };
	}
	if (req?.method === "tools/list") {
		const tools = registry.list().filter((a: any) => a.tool && !a.tool.hidden).map((a: any) => ({
			name: a.name, description: a.description ?? "",
			inputSchema:  a.input?.schema  ?? { type: "object" },
			outputSchema: a.output?.schema ?? { type: "null" },
		}));
		return { jsonrpc: "2.0", id, result: { tools } };
	}
	if (req?.method === "tools/call") {
		const name = req.params?.name;
		const args = req.params?.arguments;
		const action = registry.get(name);
		if (!action) return { jsonrpc: "2.0", id, error: { code: -32601, message: `unknown tool: ${name}` } };
		const result = await action.run({ input: args, ctx: {} });
		return { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result } };
	}
	return { jsonrpc: "2.0", id, error: { code: -32601, message: `unknown method: ${req?.method}` } };
}

async function worker() {
	console.log("[vyn] worker: booting app and running flush loop");
	process.env.VYN_WORKER = "1";
	await import(`${cwd}/server.ts`);
	// flushNow lives on the notification runtime; the worker process just
	// imports server.ts to wire installNotify(...) and then runs forever.
	process.on("SIGTERM", () => { console.log("[vyn worker] shutting down"); process.exit(0); });
	await new Promise(() => undefined);
}

// ─── gen — scan filesystem, emit _vyn.gen.ts ─────────────────────────

async function gen() {
	const featuresDir = join(cwd, "features");
	const routesDir   = join(cwd, "public", "routes");
	const actionFiles = existsSync(featuresDir) ? await walkFiles(featuresDir, /\.actions\.ts$/) : [];
	const routeFiles  = existsSync(routesDir)   ? await walkFiles(routesDir,   /\.html$/) : [];

	const lines: string[] = [
		"// generated by 'vyn gen' — do not edit.",
		"// Imports every *.actions.ts so primitives register themselves.",
		"",
	];

	for (const f of actionFiles) {
		const rel = "./" + relative(cwd, f).replace(/\\/g, "/");
		lines.push(`import "${rel}";`);
	}

	lines.push("");
	lines.push("// Route table — used by the client router.");
	lines.push(`export const routes: Array<{ pattern: string; file: string }> = [`);
	for (const f of routeFiles) {
		const rel = relative(routesDir, f).replace(/\\/g, "/").replace(/\.html$/, "");
		const pattern = "/" + rel.replace(/\[([^\]]+)\]/g, ":$1").replace(/index$/, "");
		lines.push(`\t{ pattern: ${JSON.stringify(pattern || "/")}, file: ${JSON.stringify("/routes/" + relative(routesDir, f).replace(/\\/g, "/"))} },`);
	}
	lines.push("];");
	lines.push("");
	lines.push("export type AppRouter = unknown;  // refined at typecheck time from action types");
	lines.push("");

	await writeFile(join(cwd, "_vyn.gen.ts"), lines.join("\n"));
	console.log(`[vyn] gen: wrote _vyn.gen.ts (${actionFiles.length} actions, ${routeFiles.length} routes)`);
}

async function walkFiles(dir: string, pattern: RegExp): Promise<string[]> {
	const entries = await readdir(dir);
	const out: string[] = [];
	for (const name of entries) {
		const full = join(dir, name);
		const s = await stat(full);
		if (s.isDirectory()) out.push(...await walkFiles(full, pattern));
		else if (pattern.test(name)) out.push(full);
	}
	return out;
}

main().catch((e) => { console.error("[vyn]", e); process.exit(1); });
