#!/usr/bin/env -S deno run -A --unstable-node-globals --unstable-bare-node-builtins
// vyn CLI — Deno-only. Subcommands: init, dev, build, check, gen, mcp, worker.

import { mkdir, writeFile, readdir, stat, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, relative, basename } from "node:path";
import { encodeHex } from "jsr:@std/encoding@^1/hex";

const cwd = Deno.cwd();
const argv = Deno.args.slice();
const cmd = argv[0];

async function main() {
	switch (cmd) {
		case "init":   return init();
		case "dev":    return dev();
		case "build":  return build();
		case "check":  return check();
		case "gen":    return gen();
		case "mcp":    return mcp();
		case "worker": return worker();
		default:
			help();
			Deno.exit(cmd ? 1 : 0);
	}
}

function help() {
	console.log(`vyn — small full-stack framework

Usage:
  vyn init                  scaffold a hello-world app in the current dir
  vyn dev                   run the dev server (watch + reload)
  vyn build                 build the production bundle
  vyn check                 type-check the project ('deno check')
  vyn gen                   regenerate _vyn.gen.ts (action barrel + routes)
  vyn mcp --stdio           expose the app's MCP server on stdio
  vyn worker                run the job worker (no HTTP server)
`);
}

// ─── init ────────────────────────────────────────────────────────────

async function init() {
	const name = basename(cwd);
	const files: Array<[string, string]> = [
		["deno.json", JSON.stringify({
			tasks: {
				dev:   "deno run -A --watch --unstable-node-globals --unstable-bare-node-builtins server.ts",
				start: "deno run -A --unstable-node-globals --unstable-bare-node-builtins server.ts",
				gen:   "vyn gen",
				check: "deno check server.ts",
			},
			imports: {
				"@vynjs/core":   "jsr:@vynjs/core",
				"@vynjs/server": "jsr:@vynjs/server",
				"@vynjs/client": "jsr:@vynjs/client",
			},
			nodeModulesDir: "auto",
			compilerOptions: { lib: ["deno.window", "dom", "dom.iterable", "esnext"], strict: true },
			unstable: ["node-globals", "bare-node-builtins"],
		}, null, 2)],
		["server.ts", `import { serve } from "@vynjs/server";
import "./_vyn.gen.ts";

serve({ port: Number(Deno.env.get("PORT") ?? 8000) });
`],
		["public/index.html", `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>${name}</title><link rel="stylesheet" href="/style.css"></head>
<body><main>Hello from Vyn.</main><script type="module" src="/main.js"></script></body>
</html>
`],
		["public/main.js",   `console.log("hello vyn");`],
		["public/style.css", `body { font-family: system-ui, sans-serif; padding: 2rem; }`],
		["_vyn.gen.ts",      `// generated by 'vyn gen' — do not edit.\nexport {};\n`],
	];

	for (const [path, content] of files) {
		const full = join(cwd, path);
		if (existsSync(full)) { console.log(`skip ${path} (exists)`); continue; }
		await mkdir(dirname(full), { recursive: true });
		await writeFile(full, content);
		console.log(`create ${path}`);
	}
	console.log("\nDone. Next: deno task dev");
}

// ─── dev ─────────────────────────────────────────────────────────────

async function dev() {
	await gen();
	const port = Deno.env.get("PORT") ?? "8000";

	// Watch features/ + public/routes/ for new files; re-run gen.
	const watchTargets = [join(cwd, "features"), join(cwd, "public", "routes")].filter((p) => existsSync(p));
	void watchAndGen(watchTargets);

	const proc = new Deno.Command("deno", {
		args: ["run", "-A", "--watch", "--unstable-node-globals", "--unstable-bare-node-builtins", "server.ts"],
		stdout: "inherit",
		stderr: "inherit",
		stdin:  "inherit",
		env:    { ...Object.fromEntries(Object.entries(Deno.env.toObject())), PORT: port, NODE_ENV: "development" },
	}).spawn();
	const { code } = await proc.status;
	Deno.exit(code);
}

async function watchAndGen(targets: string[]) {
	if (targets.length === 0) return;
	const watcher = Deno.watchFs(targets);
	let pending: number | undefined;
	for await (const ev of watcher) {
		const interesting = ev.paths.some((p) => /\.(actions\.ts|html)$/.test(p));
		if (!interesting) continue;
		if (pending !== undefined) clearTimeout(pending);
		pending = setTimeout(() => { void gen(); }, 100);
	}
}

// ─── build / check / mcp / worker ────────────────────────────────────

async function build() {
	await gen();

	const publicDir = join(cwd, "public");
	if (!existsSync(publicDir)) {
		console.log("[vyn] build: no public/ directory — nothing to bundle.");
		return;
	}

	const entries = await walkFiles(publicDir, /\.ts$/, ["dist"]);
	if (entries.length === 0) {
		console.log("[vyn] build: no .ts entries under public/ — nothing to bundle.");
		return;
	}

	const distDir = join(publicDir, "dist");
	await rm(distDir, { recursive: true, force: true });
	await mkdir(distDir, { recursive: true });

	const { denoPlugins } = await import("jsr:@luca/esbuild-deno-loader@^0.11.0");
	const esbuild = await import("npm:esbuild@^0.24.0");
	const manifest: Record<string, string> = {};

	for (const entry of entries) {
		const relTs  = "/" + relative(publicDir, entry).replace(/\\/g, "/");
		const srcUrl = relTs.replace(/\.ts$/, ".js");

		const result = await esbuild.build({
			entryPoints: [entry],
			bundle:      true,
			format:      "esm",
			platform:    "browser",
			target:      "es2022",
			write:       false,
			minify:      true,
			sourcemap:   false,
			logLevel:    "silent",
			plugins:     denoPlugins({ loader: "portable" }),
		});
		const bytes = result.outputFiles![0].contents as Uint8Array;
		const digest = await crypto.subtle.digest("SHA-256", bytes);
		const hash = encodeHex(new Uint8Array(digest)).slice(0, 10);
		const distRel = srcUrl.replace(/\.js$/, `.${hash}.js`);
		const outPath = join(distDir, distRel);
		await mkdir(dirname(outPath), { recursive: true });
		await writeFile(outPath, bytes);
		manifest[srcUrl] = "/dist" + distRel;
		console.log(`  ${srcUrl} → ${manifest[srcUrl]} (${bytes.length} bytes)`);
	}

	await writeFile(join(distDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
	console.log(`\n[vyn] build: ${entries.length} bundles → public/dist/, manifest at public/dist/manifest.json`);
}

async function check() {
	const proc = new Deno.Command("deno", { args: ["check", "server.ts"], stdout: "inherit", stderr: "inherit" }).spawn();
	const { code } = await proc.status;
	Deno.exit(code);
}

async function mcp() {
	const stdio = argv.includes("--stdio");
	if (!stdio) {
		console.log("[vyn] usage: vyn mcp --stdio");
		Deno.exit(1);
	}
	// Boot the app's server.ts so actions register, but never bind a port —
	// we run the MCP loop over stdin/stdout instead.
	Deno.env.set("VYN_MCP_STDIO", "1");
	Deno.env.set("PORT", "0");
	await import(`${cwd}/server.ts`);

	const { registry } = await import("@vynjs/core");
	const decoder = new TextDecoder();
	const buf = new Uint8Array(1024 * 64);
	let pending = "";
	while (true) {
		const n = await Deno.stdin.read(buf);
		if (n === null) break;
		pending += decoder.decode(buf.subarray(0, n), { stream: true });
		let nl: number;
		while ((nl = pending.indexOf("\n")) !== -1) {
			const line = pending.slice(0, nl).trim();
			pending = pending.slice(nl + 1);
			if (!line) continue;
			try {
				const req = JSON.parse(line);
				const res = await handleStdioFrame(req, registry);
				await Deno.stdout.write(new TextEncoder().encode(JSON.stringify(res) + "\n"));
			} catch (e) {
				await Deno.stdout.write(new TextEncoder().encode(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32603, message: (e as Error).message } }) + "\n"));
			}
		}
	}
}

async function handleStdioFrame(req: any, registry: any) {
	const id = req?.id;
	if (req?.method === "initialize") {
		return { jsonrpc: "2.0", id, result: { protocolVersion: "2024-11-05", capabilities: { tools: {} }, serverInfo: { name: "@vynjs/cli mcp", version: "0.0.0" } } };
	}
	if (req?.method === "tools/list") {
		const tools = registry.list().filter((a: any) => a.tool && !a.tool.hidden).map((a: any) => ({
			name: a.name, description: a.description ?? "",
			inputSchema:  a.input?.schema  ?? { type: "object" },
			outputSchema: a.output?.schema ?? { type: "null" },
		}));
		return { jsonrpc: "2.0", id, result: { tools } };
	}
	if (req?.method === "tools/call") {
		const name = req.params?.name;
		const args = req.params?.arguments;
		const action = registry.get(name);
		if (!action) return { jsonrpc: "2.0", id, error: { code: -32601, message: `unknown tool: ${name}` } };
		const result = await action.run({ input: args, ctx: {} });
		return { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result } };
	}
	return { jsonrpc: "2.0", id, error: { code: -32601, message: `unknown method: ${req?.method}` } };
}

async function worker() {
	console.log("[vyn] worker: booting app and running flush loop");
	Deno.env.set("VYN_WORKER", "1");
	await import(`${cwd}/server.ts`);
	Deno.addSignalListener("SIGTERM", () => { console.log("[vyn worker] shutting down"); Deno.exit(0); });
	await new Promise(() => undefined);
}

// ─── gen — scan filesystem, emit _vyn.gen.ts ─────────────────────────

async function loadVynConfig(): Promise<{ actionsRoot?: string; routesRoot?: string }> {
	const path = join(cwd, "vyn.config.ts");
	if (!existsSync(path)) return {};
	try {
		const mod = await import(path);
		return (mod.default ?? {}) as { actionsRoot?: string; routesRoot?: string };
	} catch (e) {
		console.warn(`[vyn] could not load vyn.config.ts: ${(e as Error).message}`);
		return {};
	}
}

async function gen() {
	const config      = await loadVynConfig();
	const featuresDir = join(cwd, config.actionsRoot ?? "features");
	const routesDir   = join(cwd, config.routesRoot  ?? "public/routes");
	const actionFiles = existsSync(featuresDir) ? await walkFiles(featuresDir, /\.actions\.ts$/) : [];
	const routeFiles  = existsSync(routesDir)   ? await walkFiles(routesDir,   /\.html$/) : [];

	const lines: string[] = [
		"// generated by 'vyn gen' — do not edit.",
		"// Imports every *.actions.ts so primitives register themselves.",
		"",
	];

	for (const f of actionFiles) {
		const rel = "./" + relative(cwd, f).replace(/\\/g, "/");
		lines.push(`import "${rel}";`);
	}

	lines.push("");
	lines.push("// Route table — used by the client router.");
	lines.push(`export const routes: Array<{ pattern: string; file: string }> = [`);
	for (const f of routeFiles) {
		const rel = relative(routesDir, f).replace(/\\/g, "/").replace(/\.html$/, "");
		const pattern = "/" + rel.replace(/\[([^\]]+)\]/g, ":$1").replace(/index$/, "");
		lines.push(`\t{ pattern: ${JSON.stringify(pattern || "/")}, file: ${JSON.stringify("/routes/" + relative(routesDir, f).replace(/\\/g, "/"))} },`);
	}
	lines.push("];");
	lines.push("");
	lines.push("export type AppRouter = unknown;  // refined at typecheck time from action types");
	lines.push("");

	await writeFile(join(cwd, "_vyn.gen.ts"), lines.join("\n"));
	console.log(`[vyn] gen: wrote _vyn.gen.ts (${actionFiles.length} actions, ${routeFiles.length} routes)`);
}

async function walkFiles(dir: string, pattern: RegExp, skipDirs: string[] = []): Promise<string[]> {
	const entries = await readdir(dir);
	const out: string[] = [];
	for (const name of entries) {
		if (skipDirs.includes(name)) continue;
		const full = join(dir, name);
		const s = await stat(full);
		if (s.isDirectory()) out.push(...await walkFiles(full, pattern, skipDirs));
		else if (pattern.test(name)) out.push(full);
	}
	return out;
}

main().catch((e) => { console.error("[vyn]", e); Deno.exit(1); });
