// generated by 'vyn gen' — do not edit.
// Imports every *.actions.ts so primitives register themselves,
// and surfaces their types as AppRouter for the typed RPC client.

import * as $hello_0 from "./features/hello/hello.actions.ts";

// Route table — used by the client router.
export const routes: Array<{ pattern: string; file: string }> = [
];

export type AppRouter = {
	"hello": (typeof $hello_0);
};
