// Walk packages/cli/template/ and bake every file into a single
// TS map at packages/cli/src/templates.gen.ts. The CLI's `init`
// reads from that map at scaffold time, so the scaffolded output
// is byte-for-byte identical to what the template directory ships
// (minus generated files and the workspace-only deno.json, which
// init() writes programmatically).
//
// Run with `deno task build:templates` from the repo root.

import { walk } from "jsr:@std/fs@^1/walk";
import { dirname, fromFileUrl, join, relative } from "jsr:@std/path@^1";

const ROOT = dirname(dirname(fromFileUrl(import.meta.url))); // packages/cli
const TEMPLATE = join(ROOT, "template");
const OUT = join(ROOT, "src", "templates.gen.ts");

// Files generated at app boot or specific to the workspace; init()
// emits its own versions or doesn't need them.
const SKIP = new Set([
	"deno.json",
	"_vyn.gen.ts",
	"_vyn.client.gen.ts",
	"README.md",
]);
const SKIP_DIRS = new Set(["node_modules", "dist", ".deno"]);

const entries: Array<[string, string]> = [];

for await (
	const entry of walk(TEMPLATE, {
		includeDirs: false,
		skip: [/\/node_modules\//, /\/dist\//, /\/\.deno\//],
	})
) {
	const rel = relative(TEMPLATE, entry.path).replaceAll("\\", "/");
	if (SKIP.has(rel)) continue;
	if (rel.split("/").some((seg) => SKIP_DIRS.has(seg))) continue;
	const content = await Deno.readTextFile(entry.path);
	entries.push([rel, content]);
}

entries.sort(([a], [b]) => a.localeCompare(b));

const lines = [
	"// AUTO-GENERATED by packages/cli/scripts/build-templates.ts",
	"// Source: packages/cli/template/  —  edit the template, then run",
	"//   deno task build:templates",
	"",
	"export const TEMPLATES: Record<string, string> = {",
];
for (const [path, content] of entries) {
	lines.push(`\t${JSON.stringify(path)}: ${JSON.stringify(content)},`);
}
lines.push("};", "");

await Deno.writeTextFile(OUT, lines.join("\n"));
console.log(`wrote ${OUT}  (${entries.length} files)`);
